services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins:/var/jenkins_home
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - data:/opt/sonarqube/data
      - logs:/opt/sonarqube/logs
      - extensions:/opt/sonarqube/extensions
  tomcat:
    image: tomee:9.1-jre11-Semeru-webprofile
    ports:
      - "8888:8080"
    volumes:
      - tomee:/usr/local/tomee
  nexus:
    image: sonatype/nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus:/opt/sonatype/nexus
volumes:
  jenkins:
  data:
  logs:
  extensions:
  tomee:
  nexus:
